//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_queue_link
    {
        public int q_id { get; set; }
        public string link_to { get; set; }
        public int link_id { get; set; }
        public System.DateTime as_of_date { get; set; }
    }
}
