//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categories()
        {
            this.teams = new HashSet<teams>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public Nullable<System.DateTime> cat_start_time { get; set; }
        public Nullable<int> cat_time_limit { get; set; }
        public Nullable<bool> valid { get; set; }
        public System.DateTime as_of_date { get; set; }
        public Nullable<bool> force_order { get; set; }
        public Nullable<int> first_start_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teams> teams { get; set; }
    }
}
