//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public competitors()
        {
            this.legs = new HashSet<legs>();
        }
    
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string bib { get; set; }
        public Nullable<int> comp_chip_id { get; set; }
        public Nullable<bool> rented_chip { get; set; }
        public Nullable<int> team_id { get; set; }
        public int rank_order { get; set; }
        public bool comp_withdrawn { get; set; }
        public string comp_status { get; set; }
        public Nullable<bool> comp_valid_flag { get; set; }
        public string comp_club { get; set; }
        public string comp_reg { get; set; }
        public string comp_country { get; set; }
        public Nullable<System.DateTime> comp_birthday { get; set; }
        public System.DateTime as_of_date { get; set; }
        public Nullable<System.DateTime> withdrawn_datetime { get; set; }
        public Nullable<int> comp_id_previous { get; set; }
    
        public virtual teams teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<legs> legs { get; set; }
    }
}
