//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class controls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public controls()
        {
            this.course_codes = new HashSet<course_codes>();
        }
    
        public string control_id { get; set; }
        public string control_code { get; set; }
        public string alt_code { get; set; }
        public string time_direction { get; set; }
        public Nullable<int> dif_hour { get; set; }
        public Nullable<int> dif_min { get; set; }
        public Nullable<int> dif_sec { get; set; }
        public System.DateTime as_of_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_codes> course_codes { get; set; }
    }
}
