//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_codes
    {
        public int cc_id { get; set; }
        public int course_id { get; set; }
        public string control_id { get; set; }
        public int position { get; set; }
        public Nullable<bool> cc_status { get; set; }
        public System.DateTime as_of_date { get; set; }
    
        public virtual controls controls { get; set; }
        public virtual courses courses { get; set; }
    }
}
