//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry_xml
    {
        public int id { get; set; }
        public string class_name { get; set; }
        public string team_name { get; set; }
        public string team_short_name { get; set; }
        public Nullable<int> leg { get; set; }
        public string family { get; set; }
        public string given { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string birth_date { get; set; }
        public Nullable<int> si_chip { get; set; }
        public string note { get; set; }
        public int oris_team_id { get; set; }
        public int team_bib { get; set; }
        public string bib { get; set; }
    }
}
