//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class legs
    {
        public int leg_id { get; set; }
        public int comp_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> readout_id { get; set; }
        public Nullable<System.DateTime> start_dtime { get; set; }
        public string start_time { get; set; }
        public Nullable<System.DateTime> finish_dtime { get; set; }
        public string finish_time { get; set; }
        public System.DateTime as_of_date { get; set; }
        public string leg_status { get; set; }
        public Nullable<System.TimeSpan> dsk_penalty { get; set; }
        public Nullable<bool> valid_flag { get; set; }
        public string leg_time { get; set; }
        public Nullable<bool> starting_leg { get; set; }
    
        public virtual competitors competitors { get; set; }
        public virtual courses courses { get; set; }
    }
}
