//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int logs_id { get; set; }
        public System.DateTime logs_time { get; set; }
        public string logs_message { get; set; }
        public string logs_type { get; set; }
        public System.DateTime as_of_date { get; set; }
    }
}
