//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class roc_punches
    {
        public int p_id { get; set; }
        public int CodeNr { get; set; }
        public int ChipNr { get; set; }
        public Nullable<System.DateTime> PunchTime { get; set; }
        public string status { get; set; }
        public System.DateTime as_of_date { get; set; }
    }
}
