//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int s_id { get; set; }
        public string config_name { get; set; }
        public string config_value { get; set; }
        public System.DateTime as_of_date { get; set; }
    }
}
