//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class si_readout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public si_readout()
        {
            this.si_stamps = new HashSet<si_stamps>();
        }
    
        public int readout_id { get; set; }
        public string chip_id { get; set; }
        public System.DateTime card_readout_datetime { get; set; }
        public Nullable<System.DateTime> clear_datetime { get; set; }
        public Nullable<System.DateTime> check_datetime { get; set; }
        public Nullable<System.DateTime> finish_datetime { get; set; }
        public Nullable<int> punch_count { get; set; }
        public System.DateTime as_of_date { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<bool> finish_missing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<si_stamps> si_stamps { get; set; }
    }
}
