//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class si_stamps
    {
        public int id_stamp { get; set; }
        public int readout_id { get; set; }
        public long chip_id { get; set; }
        public string control_code { get; set; }
        public int control_mode { get; set; }
        public Nullable<System.DateTime> punch_datetime { get; set; }
        public string punch_wday { get; set; }
        public Nullable<int> punch_index { get; set; }
        public System.DateTime as_of_date { get; set; }
    
        public virtual si_readout si_readout { get; set; }
    }
}
