//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class slips
    {
        public int slip_id { get; set; }
        public int comp_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public int course_id { get; set; }
        public string course_name { get; set; }
        public int readout_id { get; set; }
        public int chip_id { get; set; }
        public int leg_id { get; set; }
        public string comp_name { get; set; }
        public string bib { get; set; }
        public string comp_country { get; set; }
        public Nullable<bool> rented_chip { get; set; }
        public Nullable<int> team_nr { get; set; }
        public string team_name { get; set; }
        public string cat_name { get; set; }
        public Nullable<int> punch_index { get; set; }
        public string control_code { get; set; }
        public Nullable<System.DateTime> punch_dtime { get; set; }
        public string punch_time { get; set; }
        public Nullable<System.TimeSpan> lap_dtime { get; set; }
        public string lap_time { get; set; }
        public Nullable<bool> valid_flag { get; set; }
        public Nullable<System.DateTime> clear_dtime { get; set; }
        public string clear_time { get; set; }
        public Nullable<System.DateTime> check_dtime { get; set; }
        public string check_time { get; set; }
        public Nullable<System.DateTime> start_dtime { get; set; }
        public Nullable<System.DateTime> finish_dtime { get; set; }
        public string leg_time { get; set; }
        public Nullable<System.DateTime> stamp_readout_dtime { get; set; }
        public System.DateTime as_of_date { get; set; }
        public Nullable<int> position { get; set; }
        public string leg_status { get; set; }
        public Nullable<System.TimeSpan> dsk_penalty { get; set; }
        public Nullable<System.DateTime> team_race_end { get; set; }
        public string team_race_end_zero { get; set; }
        public Nullable<int> course_length { get; set; }
        public Nullable<int> course_climb { get; set; }
    }
}
