//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teams()
        {
            this.competitors = new HashSet<competitors>();
        }
    
        public int team_id { get; set; }
        public Nullable<int> team_nr { get; set; }
        public string team_name { get; set; }
        public string team_abbr { get; set; }
        public Nullable<int> cat_id { get; set; }
        public bool team_did_start { get; set; }
        public string team_status { get; set; }
        public System.DateTime as_of_date { get; set; }
        public Nullable<System.DateTime> race_end { get; set; }
        public Nullable<int> oris_id { get; set; }
        public string phone_number { get; set; }
    
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<competitors> competitors { get; set; }
    }
}
