//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_comp_teams
    {
        public Nullable<int> team_nr { get; set; }
        public string team_name { get; set; }
        public bool team_did_start { get; set; }
        public string team_status { get; set; }
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string bib { get; set; }
        public Nullable<int> comp_chip_id { get; set; }
        public Nullable<bool> rented_chip { get; set; }
        public int rank_order { get; set; }
        public bool comp_withdrawn { get; set; }
        public string comp_status { get; set; }
        public Nullable<bool> comp_valid_flag { get; set; }
        public Nullable<System.DateTime> withdrawn_datetime { get; set; }
        public int team_id { get; set; }
        public Nullable<System.DateTime> race_end { get; set; }
        public string comp_country { get; set; }
        public Nullable<System.DateTime> comp_birthday { get; set; }
        public string cat_name { get; set; }
        public Nullable<System.DateTime> cat_start_time { get; set; }
        public Nullable<int> cat_time_limit { get; set; }
        public int cat_id { get; set; }
    }
}
