//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_new_roc_punches
    {
        public int record_id { get; set; }
        public int control_code { get; set; }
        public int chip_id { get; set; }
        public Nullable<System.DateTime> punch_date { get; set; }
        public string cat_name { get; set; }
        public Nullable<int> team_nr { get; set; }
        public string team_name { get; set; }
        public string comp_name { get; set; }
        public string bib { get; set; }
        public string phone_number { get; set; }
    }
}
