//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_readout_legs
    {
        public int readout_id { get; set; }
        public string chip_id { get; set; }
        public System.DateTime card_readout_datetime { get; set; }
        public Nullable<int> comp_id { get; set; }
        public string start_time { get; set; }
        public string finish_time { get; set; }
        public string leg_time { get; set; }
        public string leg_status { get; set; }
        public Nullable<System.TimeSpan> dsk_penalty { get; set; }
        public string comp_name { get; set; }
        public Nullable<int> rank_order { get; set; }
        public string bib { get; set; }
        public string course_name { get; set; }
        public string team { get; set; }
        public Nullable<int> leg_id { get; set; }
        public Nullable<bool> valid_flag { get; set; }
        public Nullable<bool> race_valid { get; set; }
        public Nullable<int> team_id { get; set; }
    }
}
